### PR TITLE
Assorted tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
I split and adapted the patches from #28 so that we can land this and have a patch version.

Test run: https://github.com/XhmikosR/node-source-walk/actions?query=branch%3Adev-1

/CC @mrjoelkemp

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mrjoelkemp friendly ping :)

I've made PRs in all node-precinct's dependencies and you should be able to cut new patch releases after this PR is addressed and I update the other packages to use the new version of node-source-walk in my PRs.

**Review by mrjoelkemp — APPROVED** [review]

**Comment by mrjoelkemp** [comment]
> @mrjoelkemp friendly ping :)
> 
> I've made PRs in all node-precinct's dependencies and you should be able to cut new patch releases after this PR is addressed and I update the other packages to use the new version of node-source-walk in my PRs.

Thank you!

**Comment by XhmikosR** [comment]
@mrjoelkemp I think this is broken, sorry about that. Getting failures on the other repos:

```
     AssertionError [ERR_ASSERTION]: Got unwanted exception.
Actual message: "Cannot create property 'parent' on number '0'"
```

Trying to fix this as we speak.

**Comment by mrjoelkemp** [comment]
You should have permissions to push and publish fixes. Feel free.

**Comment by XhmikosR** [comment]
I'm not sure if it's a bug per se, being that and empty string is a string so the typeof check is passing (for example in node-detective-scss):

```js
module.exports = function detective(fileContent) {
  if (typeof fileContent === 'undefined') throw new Error('content not given');
  if (typeof fileContent !== 'string') throw new Error('content is not a string');
  // ...
}
```

Regardless, I think I'm going to revert the strict mode change and publish a patch version until I figure this out.

**Pull request merged**
